Add translation of DateTime.AddMillisecond
PomeloFoundation/Pomelo.EntityFrameworkCore.MySql pull request #1497
Opened 2021-08-30 11:32 UTC by iamSmallY

close #1496 

I use 
```mysql
date_add(@dt, interval num * 1000 microsecond);
```
to translate the
```C#
dt.AddMillisecond(num);
```

Since the `AddMillisecond` method will round the parameter to the nearest integer, I also add four tests for round up and round down.

2021-09-05 00:33 UTC, lauxjpn requested changes
Thanks for adding the translation!
The SQL Server provider implements it as well.

2021-09-05 00:33 UTC, lauxjpn commented on src/EFCore.MySql/Query/Internal/MySqlDateTimeMethodTranslator.cs
> +                                            new SqlConstantExpression(Expression.Constant(1000), new IntTypeMapping("int")),
Please use `_sqlExpressionFactory.Constant(1000)` here.

2021-09-05 02:31 UTC, lauxjpn requested changes
Also please rebase your changes on top of `master`, instead of `5.0-maint`. Thanks!

2021-09-05 02:31 UTC, lauxjpn commented on src/EFCore.MySql/Query/Internal/MySqlDateTimeMethodTranslator.cs
> +                                            _sqlExpressionFactory.Constant(1000, new IntTypeMapping("int32", DbType.Int32)),
Is the explicit type mapping really necessary? I would have assumed, that it works just fine without it.

2021-09-05 13:54 UTC, lauxjpn requested changes

2021-09-05 13:54 UTC, lauxjpn commented on src/EFCore.MySql/Query/Internal/MySqlDateTimeMethodTranslator.cs
> +using Microsoft.EntityFrameworkCore.Storage;
The two additional `using` statements should not be needed in the current code.

2021-09-05 21:27 UTC, lauxjpn approved these changes

2021-09-05 21:29 UTC, merged

2021-09-05 21:29 UTC, lauxjpn commented
@iamSmallY Thank you for your contribution!

2021-09-06 00:04 UTC, iamSmallY commented
No thanks😀