Let EntityFrameworkCore assign an unique alias
PomeloFoundation/Pomelo.EntityFrameworkCore.MySql pull request #1681
Opened 2022-07-09 11:53 UTC by TheConstructor

As mentioned in #1531, we can actually let EntityFramework Core assign an alias. This probably didn't work always without `.PushdownIntoSubquery()`, as the `SelectExpression` itself needs an alias for EF Core to add column-aliases, but sub-queries always need an alias and so this works now.

2022-07-14 20:24 UTC, lauxjpn requested changes
@TheConstructor Looks good, just adjust the expected SQL of the `ComplexNavigationsCollectionsSplitQueryMySqlTest.Include_collection_with_groupby_in_subquery_and_filter_after_groupby()` test and we can merge this!

```
[xUnit.net 00:05:32.40]     Pomelo.EntityFrameworkCore.MySql.FunctionalTests.Query.ComplexNavigationsCollectionsSplitQueryMySqlTest.Include_collection_with_groupby_in_subquery_and_filter_after_groupby(async: True) [FAIL]
  Failed Pomelo.EntityFrameworkCore.MySql.FunctionalTests.Query.ComplexNavigationsCollectionsSplitQueryMySqlTest.Include_collection_with_groupby_in_subquery_and_filter_after_groupby(async: False) [25 ms]
  Error Message:
   Assert.Equal() Failure
                                 ↓ (pos 290)
Expected: ···.`Name` IS NULL AS `having`\n        FROM `LevelOne` AS `l`\n  ···
Actual:   ···.`Name` IS NULL AS `c`\n        FROM `LevelOne` AS `l`\n       ···
```

2022-07-15 08:25 UTC, TheConstructor commented
@lauxjpn I ran the tests locally against MySQL 5.7 and thought I caught all tests 😅 Fixed it through the online interface, as I am currently ill.

2022-07-16 08:00 UTC, lauxjpn approved these changes
Looks good now, and we wish you a quick recovery!

2022-07-16 08:04 UTC, merged

2022-07-16 08:04 UTC, lauxjpn commented
@TheConstructor Thank you for your contribution!